---
- hosts: localhost
   connection: local
   become: true
 
   tasks:
   - name: install packages
     package:
       name:
         - htop
         - tmux         
         - micro
         - net-tools
         - dnsutils
         - nmap
...
